title: Samuel's Blog
description: ""

# permalink setting for URL structure
permalink: /blog/:title/

exclude:
  - vendor
  - .bundle
  - Gemfile
  - Gemfile.lock
  - vibes-guide.md
  - lister.py
  - prep_images.py
  - vibes_sources.yml
  - vibes_sizes.yml
